# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.

# Start AeroSpace at login
start-at-login = true

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

[exec]
    inherit-env-vars = true
[exec.env-vars]
    PATH = ''\
    '/usr/local/bin/alacritty:'\
    '${PATH}'

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 6
    inner.vertical =   6
    outer.left =       0
    outer.bottom =     0
    outer.top =        25
    outer.right =      0

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
	alt-t = '''exec-and-forget osascript -e '
    tell application "Alacritty"
		activate
	end tell'
    '''

    # aerospace list-windows --focused | awk -F ' | ' '{print $1}' | xargs aerospace layout tiling --window-id
	#alt-shift-t = ['exec-and-forget open -n /Applications/Alacritty.app -e aerospace list-windows --focused | awk -F " | " "{print $1}" | xargs aerospace layout tiling --window-id']
    #alt-shift-t = 'exec-and-forget alacritty -T FLOAT_WIN'
    #alt-shift-t = '''exec-and-forget /bin/bash -c 'alacritty msg create-window --title FLOAT_WIN' '''

    #alt-shift-t = 'exec-and-forget /usr/local/bin/alacritty msg create-window --title FLOAT_WIN'
    alt-shift-t = 'exec-and-forget alacritty msg create-window --title FLOAT_WIN'

	alt-b = '''exec-and-forget osascript -e '
	tell application "Google Chrome"
		activate
	end tell'
	'''


    alt-shift-q = 'close --quit-if-last-window'

    # i3 wraps focus by default
    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'
    #alt-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    alt-semicolon = 'split horizontal'
    alt-v = 'split vertical'

    alt-f = 'fullscreen'

    alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'

    alt-shift-c = 'reload-config'

    alt-r = 'mode resize'

    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

[[on-window-detected]]
    if.window-title-regex-substring = "FLOAT_WIN"
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'org.alacritty'
    run = 'move-node-to-workspace 1'
[[on-window-detected]]
#    if.app-id = 'com.jetbrains.intellij'
    if.app-name-regex-substring = "IntelliJ IDEA|Code"
    run = 'move-node-to-workspace 2'
[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = 'move-node-to-workspace 3'
[[on-window-detected]]
    if.app-id = 'com.sequel-ace.sequel-ace'
    run = 'move-node-to-workspace 4'
[[on-window-detected]]
    if.app-id = 'com.alibaba.DingTalkMac'
    run = 'move-node-to-workspace 5'


[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
