# plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'seebi/tmux-colors-solarized'
# session save and continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

# config
set -g prefix C-s
unbind C-b
bind C-s send-prefix
set -g bell-action none
set -g mouse off
setw -g mode-keys vi
set -g base-index 1    
set -g pane-base-index 1     
set -g renumber-windows on    
#set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=21:USER}\" %H:%M %d-%b-%y"
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} %H:%M %d-%b-%y Continuum status: #{continuum_status}"

set -g status-left "#[fg=black,bg=green,bold] #S #[default] "
set-window-option -g window-status-format "#W"
set-window-option -g window-status-current-format "#W"

# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# pi 
set -g extended-keys on
set -g extended-keys-format csi-u

# tmux-continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# key map
bind-key r source-file ~/.tmux.conf

bind-key h select-pane -R
bind-key l select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U

bind-key -n M-Left previous-window
bind-key -n M-Right next-window
bind-key M-Left swap-window -t -1\; select-window -t -1
bind-key M-Right swap-window -t +1\; select-window -t +1





run '~/.tmux/plugins/tpm/tpm'
